directories:
  output: ../
  buildResources: build
electronVersion: 35.7.0
forceCodeSigning: false
appId: com.clipsync.app
productName: ClipSync
copyright: Copyright Â© 2024 ClipSync
files:
  - filter:
      - main.js
      - preload.js
      - utils/**/*
      - node_modules/**/*
win:
  signAndEditExecutable: false
  target:
    - target: nsis
      arch:
        - x64
    - target: portable
      arch:
        - x64
  icon: build/icon.ico
mac:
  target:
    - target: dmg
      arch:
        - x64
        - arm64
    - target: zip
      arch:
        - x64
        - arm64
  icon: build/icon.icns
  category: public.app-category.productivity
  entitlements: build/entitlements.mac.plist
  entitlementsInherit: build/entitlements.mac.plist
  hardenedRuntime: true
  gatekeeperAssess: false
linux:
  target:
    - target: AppImage
      arch:
        - x64
    - target: deb
      arch:
        - x64
    - target: rpm
      arch:
        - x64
  icon: build/icon.png
  category: Utility
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: ClipSync
  deleteAppDataOnUninstall: false
  runAfterFinish: true
  menuCategory: true
portable:
  artifactName: ${productName}.exe
extraResources:
  - from: ../clipsync-app/dist
    to: app
    filter:
      - '**/*'
